import { mainTitle } from '@/theme';
import React,{useState} from 'react';
import { Alert,Modal,Pressable,ScrollView,StyleSheet,Text,TouchableOpacity,View } from 'react-native';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import * as DocumentPicker from 'expo-document-picker';
import * as Clipboard from 'expo-clipboard';
import * as Linking from 'expo-linking';
import { Ionicons } from '@expo/vector-icons';
import { ThemeMode,useApp } from '@/features/AppProvider';
import { AI_IMPORT_PROMPT } from '@/features/import/aiImportPrompt';
import { assertImportFileSize } from '@/domain/import';
import { t } from '@/i18n';

const modes:ThemeMode[]=['system','light','dark'];
const modeIcons:Record<ThemeMode,React.ComponentProps<typeof Ionicons>['name']>={system:'phone-portrait-outline',light:'sunny-outline',dark:'moon-outline'};
const privacyPolicyUrl='https://oisiu.github.io/legal/privacy.html';
export default function Settings(){
  const {repo,refresh,palette:c,themeMode,setThemeMode}=useApp();
  const [showImportGuide,setShowImportGuide]=useState(false);
  const share=async(kind:'json'|'csv')=>{if(!repo)return;try{const data=await repo.export();let content:string;if(kind==='json')content=JSON.stringify(data,null,2);else{const byId=new Map(data.habits.map(h=>[h.id,h])),path=(id:string):string=>{const h=byId.get(id);return h?`${h.parentId?path(h.parentId)+' / ':''}${h.name}`:''};content=['entry_id,local_date,timezone,type,value,habit_path',...data.entries.map(e=>{const h=byId.get(e.habitId)!;return [e.id,e.localDate,e.timezone,h.type,e.value,`"${path(h.id).replaceAll('"','""')}"`].join(',')})].join('\n')}const uri=`${FileSystem.cacheDirectory}oisiu-export.${kind}`;await FileSystem.writeAsStringAsync(uri,content);await Sharing.shareAsync(uri,{mimeType:kind==='json'?'application/json':'text/csv'})}catch{Alert.alert(t('exportFailed'),t('exportFailedHelp'))}};
  const importJson=async()=>{try{const r=await DocumentPicker.getDocumentAsync({type:'application/json',copyToCacheDirectory:true});if(r.canceled)return;assertImportFileSize(r.assets[0].size);const raw=await FileSystem.readAsStringAsync(r.assets[0].uri);assertImportFileSize(raw.length);const parsed=JSON.parse(raw);Alert.alert(t('importConfirm'),t('importSummary',{habits:parsed.habits?.length??0,entries:parsed.entries?.length??0}),[{text:t('cancel'),style:'cancel'},{text:t('importAction'),onPress:async()=>{try{await repo?.import(parsed);await refresh();Alert.alert(t('importComplete'))}catch{Alert.alert(t('importRejected'),t('importFailedHelp'))}}}])}catch{Alert.alert(t('fileReadFailed'),t('fileReadHelp'))}};
  const copyPrompt=async()=>{try{await Clipboard.setStringAsync(AI_IMPORT_PROMPT);Alert.alert(t('promptCopied'),t('promptCopiedHelp'))}catch{Alert.alert(t('copyFailed'),t('copyFailedHelp'))}};
  return <><ScrollView style={[s.page,{backgroundColor:c.bg}]} contentContainerStyle={s.content}><View style={{minHeight:48,justifyContent:'center'}}><Text style={[s.title,{color:c.text}]}>{t('settings')}</Text></View><Text style={[s.sectionTitle,{color:c.text}]}>{t('appearance')}</Text><View accessibilityRole="radiogroup" style={[s.modes,{backgroundColor:c.card}]}>{modes.map(mode=>{const selected=themeMode===mode;return <TouchableOpacity accessibilityRole="radio" accessibilityLabel={t(mode)} accessibilityState={{selected}} key={mode} onPress={()=>void setThemeMode(mode)} style={[s.mode,selected&&{backgroundColor:c.accent}]}><Ionicons name={modeIcons[mode]} size={22} color={selected?'white':c.text}/></TouchableOpacity>})}</View><Text style={[s.sectionTitle,{color:c.text}]}>{t('data')}</Text><Text style={[s.intro,{color:c.muted}]}>{t('dataPrivacy')}</Text><View style={[s.card,{backgroundColor:c.card}]}><Action icon="document-text-outline" label={t('exportJson')} onPress={()=>share('json')} color={c.text}/><Action icon="grid-outline" label={t('exportCsv')} onPress={()=>share('csv')} color={c.text}/><Action icon="download-outline" label={t('importJson')} onPress={importJson} color={c.accent}/><Action icon="sparkles-outline" label={t('convertExport')} onPress={()=>setShowImportGuide(true)} color={c.text}/><Action icon="shield-checkmark-outline" label={t('privacyPolicy')} onPress={()=>void Linking.openURL(privacyPolicyUrl)} color={c.text}/></View><Text style={[s.note,{color:c.muted}]}>{t('safeMergeHelp')}</Text></ScrollView><Modal transparent visible={showImportGuide} animationType="slide" onRequestClose={()=>setShowImportGuide(false)}><Pressable style={s.overlay} onPress={()=>setShowImportGuide(false)}><Pressable style={[s.guide,{backgroundColor:c.card}]} onPress={()=>undefined}><Text style={[s.guideTitle,{color:c.text}]}>{t('convertData')}</Text><Text style={[s.guideIntro,{color:c.muted}]}>{t('convertGuide')}</Text><ScrollView style={[s.promptBox,{borderColor:c.line,backgroundColor:c.bg}]}><Text selectable style={[s.prompt,{color:c.text}]}>{AI_IMPORT_PROMPT}</Text></ScrollView><View style={s.guideActions}><TouchableOpacity accessibilityRole="button" onPress={()=>setShowImportGuide(false)} style={[s.guideButton,{backgroundColor:c.soft}]}><Text style={{color:c.text,fontWeight:'800'}}>{t('close')}</Text></TouchableOpacity><TouchableOpacity accessibilityRole="button" onPress={()=>void copyPrompt()} style={[s.guideButton,{backgroundColor:c.accent}]}><Text style={{color:'white',fontWeight:'800'}}>{t('copyPrompt')}</Text></TouchableOpacity></View></Pressable></Pressable></Modal></>;
}
function Action({icon,label,onPress,color}:{icon:React.ComponentProps<typeof Ionicons>['name'];label:string;onPress:()=>void;color:string}){return <TouchableOpacity accessibilityRole="button" onPress={onPress} style={s.action}><View style={s.actionLabel}><Ionicons name={icon} size={20} color={color}/><Text style={{color,fontSize:16,flexShrink:1}}>{label}</Text></View><Ionicons name="chevron-forward" size={18} color={color}/></TouchableOpacity>}
const s=StyleSheet.create({page:{flex:1},content:{padding:20,paddingTop:12,paddingBottom:40},title:{...mainTitle,marginBottom:2},sectionTitle:{fontSize:17,fontWeight:'800',marginTop:26,marginBottom:10},intro:{lineHeight:21,marginBottom:12},modes:{flexDirection:'row',padding:4,borderRadius:18},mode:{flex:1,minHeight:46,borderRadius:14,alignItems:'center',justifyContent:'center'},card:{borderRadius:18,overflow:'hidden'},action:{minHeight:58,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#8885'},actionLabel:{flex:1,flexDirection:'row',alignItems:'center',gap:12,paddingRight:12},note:{marginTop:14,lineHeight:20},overlay:{flex:1,justifyContent:'flex-end',backgroundColor:'#0008'},guide:{maxHeight:'88%',borderTopLeftRadius:24,borderTopRightRadius:24,padding:20,paddingBottom:28},guideTitle:{fontSize:22,fontWeight:'900'},guideIntro:{lineHeight:20,marginTop:8,marginBottom:14},promptBox:{borderWidth:1,borderRadius:14,padding:14},prompt:{fontFamily:'monospace',fontSize:12,lineHeight:18},guideActions:{flexDirection:'row',gap:10,marginTop:14},guideButton:{flex:1,minHeight:48,borderRadius:14,alignItems:'center',justifyContent:'center'}});
